name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check project structure
        run: |
          pwd
          ls -la
          ls -la app
          python --version

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m pytest -v


  docker-build:
    name: Build Docker Image
    needs: test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t car-price-api:latest .


  aws-auth:
    name: Test AWS Authentication
    needs: docker-build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::340234702228:role/GitHubActionsCarPriceAPI
          aws-region: ap-south-1

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity